### ISSUE TITLE
Deprecated library

### ISSUE THREAD

**Issue by MasterCruelty** [NespoliBT/Nespbot#1] opened 2021-04-22 13:25 UTC
This bot is using ```telepot``` as main library to get in touch with Telegram like here: [Nespbot.py](https://github.com/NespoliBT/Nespbot/blob/master/Nespbot.py)
Unfortunately this framework **is no longer maintained.**
Link to telepot repo: [here](https://github.com/nickoala/telepot)

**Comment by NespoliBT** [comment] 2021-04-22 14:03
Duplicate of [#69420](https://youtu.be/dQw4w9WgXcQ).
Closing.

**Closed as completed by NespoliBT** 2021-04-22 14:03 UTC

**Comment by MasterCruelty** [comment] 2021-04-22 14:05
AHAHAHAHAHAHAHAHAH
